1. Import the fastF1 API

Explain what an API is, the importance of API in this context, and then begin explaining how we will do it. Move on to libraries, what they are and how to import them.

In [2]:
!pip install fastf1

import os
import fastf1
cache_path = os.path.expanduser('~/Documents/BuildMLM/cache')
os.makedirs(cache_path, exist_ok=True)
fastf1.Cache.enable_cache(cache_path)

Requirement already satisfied: fastf1 in /opt/anaconda3/lib/python3.12/site-packages (3.8.1)
Requirement already satisfied: cryptography in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (42.0.5)
Requirement already satisfied: matplotlib<4.0.0,>=3.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (3.8.4)
Requirement already satisfied: numpy<3.0.0,>=1.26.0 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (1.26.4)
Requirement already satisfied: pandas<3.0.0,>=2.1.1 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (2.2.2)
Requirement already satisfied: platformdirs in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (3.10.0)
Requirement already satisfied: pydantic in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (2.5.3)
Requirement already satisfied: pyjwt in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (2.8.0)
Requirement already satisfied: python-dateutil in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (2.9.0.post0)
Requirement already satisfied: rapidfuzz in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (3.14.3)
Requirement already satisfied: requests-cache>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (1.3.1)
Requirement already satisfied: requests>=2.30.0 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (2.32.2)
Requirement already satisfied: scipy<2.0.0,>=1.11.0 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (1.13.1)
Requirement already satisfied: signalrcore in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (1.0.2)
Requirement already satisfied: timple>=0.1.6 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (0.1.8)
Requirement already satisfied: websockets>=10.3 in /opt/anaconda3/lib/python3.12/site-packages (from fastf1) (16.0)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (23.2)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (10.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from matplotlib<4.0.0,>=3.8.0->fastf1) (3.0.9)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas<3.0.0,>=2.1.1->fastf1) (2023.3)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.12/site-packages (from python-dateutil->fastf1) (1.16.0)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30.0->fastf1) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30.0->fastf1) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30.0->fastf1) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.12/site-packages (from requests>=2.30.0->fastf1) (2025.8.3)
Requirement already satisfied: attrs>=21.2 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache>=1.0.0->fastf1) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache>=1.0.0->fastf1) (26.1.0)
Requirement already satisfied: url-normalize>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from requests-cache>=1.0.0->fastf1) (2.2.1)
Requirement already satisfied: cffi>=1.12 in /opt/anaconda3/lib/python3.12/site-packages (from cryptography->fastf1) (1.16.0)
Requirement already satisfied: annotated-types>=0.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic->fastf1) (0.6.0)
Requirement already satisfied: pydantic-core==2.14.6 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic->fastf1) (2.14.6)
Requirement already satisfied: typing-extensions>=4.6.1 in /opt/anaconda3/lib/python3.12/site-packages (from pydantic->fastf1) (4.15.0)
Requirement already satisfied: msgpack==1.1.2 in /opt/anaconda3/lib/python3.12/site-packages (from signalrcore->fastf1) (1.1.2)
Requirement already satisfied: pycparser in /opt/anaconda3/lib/python3.12/site-packages (from cffi>=1.12->cryptography->fastf1) (2.21)

2. Loading the required data; in this case the 2 Practice Session for the Australian GP 2026

In [3]:

os.makedirs('cache/', exist_ok=True)
fastf1.Cache.enable_cache('cache/')

session = fastf1.get_session(2026, 'Australia', 'FP1')
session.load()

session = fastf1.get_session(2026, 'Australia', 'FP2')
session.load()

core           INFO 	Loading data for Australian Grand Prix - Practice 1 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
core        WARNING 	No lap data for driver 14
core        WARNING 	Failed to perform lap accuracy check - all laps marked as inaccurate (driver 14)
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']
core           INFO 	Loading data for Australian Grand Prix - Practice 2 [v3.8.1]
req            INFO 	No cached data found for session_info. Loading data...
_api           INFO 	Fetching session info data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for driver_info. Loading data...
_api           INFO 	Fetching driver list...
req            INFO 	Data has been written to cache!
core        WARNING 	No result data for this session available on Ergast! (This is expected for recent sessions)
req            INFO 	No cached data found for session_status_data. Loading data...
_api           INFO 	Fetching session status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for track_status_data. Loading data...
_api           INFO 	Fetching track status data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for _extended_timing_data. Loading data...
_api           INFO 	Fetching timing data...
_api           INFO 	Parsing timing data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for timing_app_data. Loading data...
_api           INFO 	Fetching timing app data...
req            INFO 	Data has been written to cache!
core           INFO 	Processing timing data...
req            INFO 	No cached data found for car_data. Loading data...
_api           INFO 	Fetching car data...
_api           INFO 	Parsing car data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for position_data. Loading data...
_api           INFO 	Fetching position data...
_api           INFO 	Parsing position data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for weather_data. Loading data...
_api           INFO 	Fetching weather data...
req            INFO 	Data has been written to cache!
req            INFO 	No cached data found for race_control_messages. Loading data...
_api           INFO 	Fetching race control messages...
req            INFO 	Data has been written to cache!
core           INFO 	Finished loading data for 22 drivers: ['1', '3', '5', '6', '10', '11', '12', '14', '16', '18', '23', '27', '30', '31', '41', '43', '44', '55', '63', '77', '81', '87']

3. Exploratory data analysis - explain the importance of understanding our data by loading various figures to get a feel for it. 

3.1 Include some visualisation techniques by importing matplotlib, seaborn, and fastf1.plotting.

In [20]:
session.laps.shape

(544, 31)

In [29]:
session.laps.describe()

,Time,LapTime,LapNumber,Stint,PitOutTime,PitInTime,Sector1Time,Sector2Time,Sector3Time,Sector1SessionTime,Sector2SessionTime,Sector3SessionTime,SpeedI1,SpeedI2,SpeedFL,SpeedST,TyreLife,LapStartTime,LapStartDate,Position
count,544,458,544.000000,544.000000,86,86,539,544,479,538,544,479,544.000000,544.000000,458.000000,544.000000,544.000000,544,544,0.0
mean,0 days 00:48:00.551568014,0 days 00:01:39.582021834,14.297794,2.693015,0 days 00:40:20.650313953,0 days 00:51:04.419604651,0 days 00:00:37.168513914,0 days 00:00:21.173196691,0 days 00:00:43.580726513,0 days 00:46:39.811557620,0 days 00:46:44.569314338,0 days 00:46:43.920764091,230.847426,260.110294,275.264192,247.101103,8.698529,0 days 00:45:46.369325367,2026-03-06 05:32:58.549325568,NaN
min,0 days 00:14:29.320000,0 days 00:01:19.729000,1.000000,1.000000,0 days 00:12:49.713000,0 days 00:19:56.286000,0 days 00:00:27.803000,0 days 00:00:17.462000,0 days 00:00:34.345000,0 days 00:14:18.977000,0 days 00:13:51.100000,0 days 00:14:29.420000,81.000000,83.000000,2.000000,60.000000,1.000000,0 days 00:12:49.713000,2026-03-06 05:00:01.893000,NaN
25%,0 days 00:29:21.721250,0 days 00:01:24.313250,7.000000,1.000000,0 days 00:23:27.486750,0 days 00:31:57.369500,0 days 00:00:29.525500,0 days 00:00:18.139250,0 days 00:00:36.515500,0 days 00:28:00.993250,0 days 00:28:10.668250,0 days 00:27:34.645000,219.000000,237.750000,275.000000,214.750000,4.000000,0 days 00:27:01.422250,2026-03-06 05:14:13.602249984,NaN
50%,0 days 00:49:03.714500,0 days 00:01:28.474000,13.500000,3.000000,0 days 00:39:29.686500,0 days 00:49:52.070000,0 days 00:00:31.085000,0 days 00:00:18.750500,0 days 00:00:38.125000,0 days 00:47:28.251500,0 days 00:47:29.568000,0 days 00:47:30.861000,247.000000,280.500000,286.000000,270.500000,7.000000,0 days 00:46:28.739500,2026-03-06 05:33:40.919500032,NaN
75%,0 days 01:04:54.917500,0 days 00:01:55.324500,21.250000,4.000000,0 days 00:55:49.801750,0 days 01:09:08.307000,0 days 00:00:40.898000,0 days 00:00:22.851250,0 days 00:00:48.004000,0 days 01:03:59.045500,0 days 01:04:10.295250,0 days 01:04:14.170000,259.000000,292.000000,296.000000,288.000000,13.000000,0 days 01:03:20.650500,2026-03-06 05:50:32.830500096,NaN
max,0 days 01:18:55.405000,0 days 00:02:29.202000,34.000000,6.000000,0 days 01:12:30.676000,0 days 01:18:55.405000,0 days 00:01:37.242000,0 days 00:00:43.316000,0 days 00:01:39.664000,0 days 01:17:36.179000,0 days 01:17:54.903000,0 days 01:17:05.499000,295.000000,316.000000,320.000000,314.000000,26.000000,0 days 01:17:05.499000,2026-03-06 06:04:17.679000,NaN
std,0 days 00:19:18.864191176,0 days 00:00:19.018366427,8.623895,1.461434,0 days 00:18:52.004068272,0 days 00:19:23.618688223,0 days 00:00:11.717683572,0 days 00:00:04.528165849,0 days 00:00:11.511518761,0 days 00:19:15.348129944,0 days 00:19:24.076637080,0 days 00:19:14.809905841,41.508843,46.156499,46.994320,53.226010,5.952631,0 days 00:19:26.565268930,NaN,NaN

In [23]:
session.laps.isnull().sum()

Time                    0
Driver                  0
DriverNumber            0
LapTime                86
LapNumber               0
Stint                   0
PitOutTime            458
PitInTime             458
Sector1Time             5
Sector2Time             0
Sector3Time            65
Sector1SessionTime      6
Sector2SessionTime      0
Sector3SessionTime     65
SpeedI1                 0
SpeedI2                 0
SpeedFL                86
SpeedST                 0
IsPersonalBest          0
Compound                0
TyreLife                0
FreshTyre               0
Team                    0
LapStartTime            0
LapStartDate            0
TrackStatus             0
Position              544
Deleted                 0
DeletedReason           0
FastF1Generated         0
IsAccurate              0
dtype: int64

In [12]:
session.laps.columns

Index(['Time', 'Driver', 'DriverNumber', 'LapTime', 'LapNumber', 'Stint',
       'PitOutTime', 'PitInTime', 'Sector1Time', 'Sector2Time', 'Sector3Time',
       'Sector1SessionTime', 'Sector2SessionTime', 'Sector3SessionTime',
       'SpeedI1', 'SpeedI2', 'SpeedFL', 'SpeedST', 'IsPersonalBest',
       'Compound', 'TyreLife', 'FreshTyre', 'Team', 'LapStartTime',
       'LapStartDate', 'TrackStatus', 'Position', 'Deleted', 'DeletedReason',
       'FastF1Generated', 'IsAccurate'],
      dtype='object')

In [17]:
session.laps["Driver"].unique()

array(['NOR', 'VER', 'BOR', 'HAD', 'GAS', 'PER', 'ANT', 'ALO', 'LEC',
       'STR', 'ALB', 'HUL', 'LAW', 'OCO', 'LIN', 'COL', 'HAM', 'SAI',
       'RUS', 'BOT', 'PIA', 'BEA'], dtype=object)

In [32]:
session.results

,DriverNumber,BroadcastName,Abbreviation,DriverId,TeamName,TeamColor,TeamId,FirstName,LastName,FullName,...,Position,ClassifiedPosition,GridPosition,Q1,Q2,Q3,Time,Status,Points,Laps
1,1,L NORRIS,NOR,,McLaren,F47600,,Lando,Norris,Lando Norris,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
3,3,M VERSTAPPEN,VER,,Red Bull Racing,4781D7,,Max,Verstappen,Max Verstappen,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
5,5,G BORTOLETO,BOR,,Audi,F50537,,Gabriel,Bortoleto,Gabriel Bortoleto,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
6,6,I HADJAR,HAD,,Red Bull Racing,4781D7,,Isack,Hadjar,Isack Hadjar,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
10,10,P GASLY,GAS,,Alpine,00A1E8,,Pierre,Gasly,Pierre Gasly,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
11,11,S PEREZ,PER,,Cadillac,909090,,Sergio,Perez,Sergio Perez,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
12,12,K ANTONELLI,ANT,,Mercedes,00D7B6,,Kimi,Antonelli,Kimi Antonelli,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
14,14,F ALONSO,ALO,,Aston Martin,229971,,Fernando,Alonso,Fernando Alonso,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
16,16,C LECLERC,LEC,,Ferrari,ED1131,,Charles,Leclerc,Charles Leclerc,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
18,18,L STROLL,STR,,Aston Martin,229971,,Lance,Stroll,Lance Stroll,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
23,23,A ALBON,ALB,,Williams,1868DB,,Alexander,Albon,Alexander Albon,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
27,27,N HULKENBERG,HUL,,Audi,F50537,,Nico,Hulkenberg,Nico Hulkenberg,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
30,30,L LAWSON,LAW,,Racing Bulls,6C98FF,,Liam,Lawson,Liam Lawson,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
31,31,E OCON,OCO,,Haas F1 Team,9C9FA2,,Esteban,Ocon,Esteban Ocon,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
41,41,A LINDBLAD,LIN,,Racing Bulls,6C98FF,,Arvid,Lindblad,Arvid Lindblad,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
43,43,F COLAPINTO,COL,,Alpine,00A1E8,,Franco,Colapinto,Franco Colapinto,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
44,44,L HAMILTON,HAM,,Ferrari,ED1131,,Lewis,Hamilton,Lewis Hamilton,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
55,55,C SAINZ,SAI,,Williams,1868DB,,Carlos,Sainz,Carlos Sainz,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
63,63,G RUSSELL,RUS,,Mercedes,00D7B6,,George,Russell,George Russell,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
77,77,V BOTTAS,BOT,,Cadillac,909090,,Valtteri,Bottas,Valtteri Bottas,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
81,81,O PIASTRI,PIA,,McLaren,F47600,,Oscar,Piastri,Oscar Piastri,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN
87,87,O BEARMAN,BEA,,Haas F1 Team,9C9FA2,,Oliver,Bearman,Oliver Bearman,...,NaN,,NaN,NaT,NaT,NaT,NaT,,NaN,NaN

In [30]:
session.laps.info()

<class 'fastf1.core.Laps'>
RangeIndex: 544 entries, 0 to 543
Data columns (total 31 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Time                544 non-null    timedelta64[ns]
 1   Driver              544 non-null    object
 2   DriverNumber        544 non-null    object
 3   LapTime             458 non-null    timedelta64[ns]
 4   LapNumber           544 non-null    float64
 5   Stint               544 non-null    float64
 6   PitOutTime          86 non-null     timedelta64[ns]
 7   PitInTime           86 non-null     timedelta64[ns]
 8   Sector1Time         539 non-null    timedelta64[ns]
 9   Sector2Time         544 non-null    timedelta64[ns]
 10  Sector3Time         479 non-null    timedelta64[ns]
 11  Sector1SessionTime  538 non-null    timedelta64[ns]
 12  Sector2SessionTime  544 non-null    timedelta64[ns]
 13  Sector3SessionTime  479 non-null    timedelta64[ns]
 14  SpeedI1             544 non-null    float64
 15  SpeedI2             544 non-null    float64
 16  SpeedFL             458 non-null    float64
 17  SpeedST             544 non-null    float64
 18  IsPersonalBest      544 non-null    bool
 19  Compound            544 non-null    object
 20  TyreLife            544 non-null    float64
 21  FreshTyre           544 non-null    bool
 22  Team                544 non-null    object
 23  LapStartTime        544 non-null    timedelta64[ns]
 24  LapStartDate        544 non-null    datetime64[ns]
 25  TrackStatus         544 non-null    object
 26  Position            0 non-null      float64
 27  Deleted             544 non-null    bool
 28  DeletedReason       544 non-null    object
 29  FastF1Generated     544 non-null    bool
 30  IsAccurate          544 non-null    bool
dtypes: bool(5), datetime64[ns](1), float64(8), object(6), timedelta64[ns](11)
memory usage: 113.3+ KB